plugin: networktocode.nautobot.gql_inventory

api_endpoint: "https://192.168.128.7/"
token: "1f1652d698bd1e519ac3bebbab09ae7eb03ccfb6"
validate_certs: false

query:
  devices:
    id: null
    name: null
    primary_ip4: host
    platform:
      napalm_driver
      network_driver

compose:
  ansible_host: primary_ip4.host
  ansible_network_os: >-
    {{
      'ale.aos8.aos8'
      if platform.napalm_driver == 'aos'
      else 'unsupported'
    }}
  ansible_connection: network_cli
  ansible_user: "admin"
  ansible_password: "switch"
  ansible_command_timeout: 60
  ansible_connect_timeout: 90

  # Make Nautobot info available to all hosts
  nautobot_host: "{{ api_endpoint | regex_replace('https?://', '') | regex_replace('/$', '') }}"
  nautobot_token: "{{ token }}"

strict: false

group_by:
  - role.name

