---
- name: Interface Update
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:

    - name: Derive address and mask from CIDR
      set_fact:
        interface_ip: "{{ ip_address | ipaddr }}"
      when: ip_address != '' and ip_address != '0.0.0.0'

    - name: Run L3 interfaces resource module with state merged
      ale.aos8.aos8_l3_interfaces:
        device: "{{ device_id }}"
        interface: "{{ interface_name }}"
        label: "{{ label }}"
        mode: "{{ mode }}"
        untagged_vlan: "{{ untagged_vlan }}"
        tagged_vlans: "{{ tagged_vlans }}"
        description: "{{ description }}"
        enabled: "{{ enabled }}"
        ip_address: "{{ interface_ip | default(omit) }}"
        physical_port: "{{ physical_port }}"
        type: "{{ int_type }}"
      when: int_type is defined and int_type != ''

