---
- name: Interface Update
  hosts: "{{ device_id }}"
  gather_facts: no
  vars:
    ansible_remote_tmp: /tmp/.ansible/tmp
  tasks:

    - name: Ensure IP address is defined
      debug:
        msg: "ip_address is empty, skipping CIDR processing"
      when: ip_address == "" or ip_address is not defined

    - name: Derive address and mask from CIDR
      set_fact:
        l3_addr: "{{ ip_address.split('/')[0] }}"
        l3_mask: "{{ ('0.0.0.0/' ~ ip_address.split('/')[1]) | ansible.utils.ipaddr('netmask') }}"
      when: ip_address != "" and ip_address is defined

    - name: Debug derived values
      debug:
        msg: "Device {{ inventory_hostname }} -> addr={{ l3_addr | default('N/A') }}, mask={{ l3_mask | default('N/A') }}"

    - name: Run L3 interfaces resource module with state merged
      ale.aos8.aos8_l3_interfaces:
        config:
          - name: "{{ interface_id }}"
            address: "{{ l3_addr | default(omit) }}"
            mask: "{{ l3_mask | default(omit) }}"
              #type: "{{ default('vlan') }}"
            port_id: "{{ tagged_vlans }}"
        state: merged
      when: ip_address != "" and ip_address is defined

