---
- name: Interface Update
  hosts: "{{ device_id }}"
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  tasks:

    - name: Ensure IP address is defined
      fail:
        msg: "ip_address is undefined for {{ inventory_hostname }}"
      when: ip_address is not defined

    - name: Derive address and mask from CIDR
      set_fact:
        l3_addr: "{{ ip_address.split('/')[0] }}"
        l3_mask: >-
          {% set prefix = ip_address.split('/')[1] | int %}
          {% set mask = (0xffffffff << (32 - prefix)) & 0xffffffff %}
          {{ ((mask >> 24) & 255) ~ '.' ~ ((mask >> 16) & 255) ~ '.' ~ ((mask >> 8) & 255) ~ '.' ~ (mask & 255) }}

    - name: Run L3 interfaces resource module with state merged
      ale.aos8.aos8_l3_interfaces:
        config:
          - iface_name: "{{ interface_id }}"   # éviter warning "name"
            address: "{{ l3_addr }}"
            mask: "{{ l3_mask }}"
            type: "{{ int_type | default('ethernet') }}"
            port_id: "{{ tagged_vlans }}"
        state: merged

