---
- name: Nautobot Webhook interface update
  hosts: "{{ device_id }}"
  gather_facts: no
  connection: network_cli
  vars:
    ansible_remote_tmp: /tmp/.ansible/tmp
  ignore_errors: true

  # become: true
  
  roles:
  - { role: ../role/task/config_update_interface.yaml }
