---
- name: Nautobot Webhook VLAN update
  hosts: "{{ device_id }}"
  gather_facts: no
  connection: network_cli
  vars:
    ansible_remote_tmp: /tmp/.ansible/tmp
  ignore_errors: true

  roles:
    - { role: updates_from_nautobot/update_l2_ports }

